/**
 * §9.1 step 2 — emits src/data/learn/demandsManifest.ts, the client-facing
 * index the trust boundary is built on. `demandsVersion` is a SHA-256 hex
 * digest over the corpus's own file bytes (sorted by filename): since
 * backend/data/learn/ is a byte-for-byte copy of src/data/learn/demands/
 * (step 3 of §9.1), hashing the raw file contents is "the same way" the
 * backend computes its hash — no bespoke canonicalization scheme is needed
 * because both sides hash literally the same bytes, not a re-derived
 * in-memory structure (unlike hashQuestionSet.ts, which canonicalizes
 * because the two sides start from different representations).
 *
 *   npm run learn:build-manifest
 *
 * Run after any change to src/data/learn/demands/*.json, before syncing to
 * backend/data/learn/ (§9.1 step 3) or committing.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { LearnDemandsFile, QuestionDemands } from '../../src/domain/learn/demand/types';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DATA_DIR = join(__dirname, '..', '..', 'src', 'data', 'learn', 'demands');
const OUT_FILE = join(__dirname, '..', '..', 'src', 'data', 'learn', 'demandsManifest.ts');

const SEP = String.fromCharCode(0x20);

function loadSortedFiles(dir: string): { filename: string; raw: string; parsed: LearnDemandsFile }[] {
  const filenames = readdirSync(dir).filter((f) => f.endsWith('.json')).sort();
  return filenames.map((filename) => {
    const raw = readFileSync(join(dir, filename), 'utf-8');
    return { filename, raw, parsed: JSON.parse(raw) as LearnDemandsFile };
  });
}

/** SHA-256 hex over sorted-filename-concatenated raw file bytes. */
export function hashCorpus(files: { filename: string; raw: string }[]): string {
  const hash = createHash('sha256');
  for (const { filename, raw } of files) {
    hash.update(filename);
    hash.update(SEP);
    hash.update(raw);
    hash.update(SEP);
  }
  return hash.digest('hex');
}

function main(): void {
  const files = loadSortedFiles(DATA_DIR);
  if (files.length === 0) {
    console.error(`No .json files found in ${DATA_DIR} — refusing to emit an empty manifest.`);
    process.exit(1);
  }

  const demandsVersion = hashCorpus(files);
  const byQuestionId: Record<string, QuestionDemands> = {};
  for (const { parsed } of files) {
    for (const entry of parsed.entries) {
      byQuestionId[entry.questionId] = entry.demands;
    }
  }

  const questionCount = Object.keys(byQuestionId).length;
  const body = `/**
 * GENERATED by scripts/authoring/buildDemandsManifest.ts — do not hand-edit.
 * Source: src/data/learn/demands/*.json (${files.length} files, ${questionCount} questions).
 * Regenerate with: npm run learn:build-manifest
 */
import type { QuestionDemands } from '../../domain/learn/demand/types';

export const demandsVersion = ${JSON.stringify(demandsVersion)};

export const byQuestionId: Readonly<Record<string, QuestionDemands>> = ${JSON.stringify(byQuestionId, null, 2)};
`;

  writeFileSync(OUT_FILE, body, 'utf-8');
  console.log(`Wrote ${OUT_FILE}`);
  console.log(`demandsVersion = ${demandsVersion}`);
  console.log(`${questionCount} question(s) across ${files.length} file(s).`);
}

main();
