/**
 * Generates the in-repo offline fixtures (src/data/exam/bank/fixtures/) from
 * french-coach-backend's data/igcse/*.json — the canonical authored source.
 * Never hand-edit a generated fixture: edit the JSON, re-run this, then
 * `npm run authoring:parity` confirms both sides hash identically.
 *
 *   npm run authoring:generate            # default: backend/data/igcse
 *   npm run authoring:generate -- <dir>   # override the data dir
 *
 * Each set is validated first (parseAuthoredQuestionSet), so an invalid JSON
 * file never becomes a fixture. Writes one `original-practice-0NN.ts` per set
 * plus `index.ts` (OFFLINE_FIXTURES), and deletes any stale generated fixture
 * whose JSON no longer exists.
 */
import { readdirSync, readFileSync, unlinkSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseAuthoredQuestionSet } from '../../src/data/exam/bank/validate';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DEFAULT_DATA_DIR = join(__dirname, '..', '..', 'backend', 'data', 'igcse');
const FIXTURES_DIR = join(__dirname, '..', '..', 'src', 'data', 'exam', 'bank', 'fixtures');

/** original-practice-001 -> ORIGINAL_PRACTICE_001 */
function constName(questionSetId: string): string {
  return questionSetId.toUpperCase().replace(/[^A-Z0-9]+/g, '_');
}

function renderFixture(filename: string, questionSetId: string, raw: unknown): string {
  return `/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/${filename} (the canonical authored source). Do not edit by hand:
 * edit the JSON, run \`npm run authoring:generate\`, then \`npm run authoring:parity\`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ${constName(questionSetId)}: AuthoredQuestionSet = ${JSON.stringify(raw, null, 2)};
`;
}

function renderIndex(ids: string[]): string {
  const imports = ids.map((id) => `import { ${constName(id)} } from './${id}';`).join('\n');
  const entries = ids.map((id) => `  [${constName(id)}.questionSetId]: ${constName(id)},`).join('\n');
  return `/**
 * GENERATED by scripts/authoring/generateFixtures.ts — do not edit by hand.
 *
 * The in-repo offline fixture registry, keyed by questionSetId — shared by
 * the browser loader (../loader.ts) and the Node scoring service
 * (server/resolveQuestionSet.ts), so both resolve the same sets. Must stay
 * Node-safe: no import.meta.env, no browser globals (loader.ts reads
 * import.meta.env and so cannot be imported by the server).
 *
 * All published sets are bundled so a catalog-fetch failure/cold-start
 * degrades to the real picker instead of collapsing it to a single offline
 * exam (see ExamSelect.tsx). Drift from the canonical JSON is caught by
 * \`npm run authoring:parity\`.
 */

${imports}
import type { AuthoredQuestionSet } from '../types';

export const OFFLINE_FIXTURES: Readonly<Record<string, AuthoredQuestionSet>> = {
${entries}
};
`;
}

function main(): void {
  const dirArg = process.argv[2];
  const dataDir = dirArg ? resolve(process.cwd(), dirArg) : DEFAULT_DATA_DIR;

  let filenames: string[];
  try {
    filenames = readdirSync(dataDir).filter((f) => f.endsWith('.json')).sort();
  } catch {
    console.error(`No such directory: ${dataDir}`);
    process.exit(1);
  }
  if (filenames.length === 0) {
    console.error(`No .json files in ${dataDir}`);
    process.exit(1);
  }

  const ids: string[] = [];
  for (const filename of filenames) {
    const raw = JSON.parse(readFileSync(join(dataDir, filename), 'utf-8')) as unknown;
    const set = parseAuthoredQuestionSet(raw);
    if (`${set.questionSetId}.json` !== filename) {
      console.error(`${filename}: questionSetId "${set.questionSetId}" does not match its filename`);
      process.exit(1);
    }
    writeFileSync(join(FIXTURES_DIR, `${set.questionSetId}.ts`), renderFixture(filename, set.questionSetId, raw), 'utf-8');
    ids.push(set.questionSetId);
    console.log(`✓ ${set.questionSetId}`);
  }

  for (const existing of readdirSync(FIXTURES_DIR)) {
    if (existing === 'index.ts' || !existing.endsWith('.ts')) continue;
    if (!ids.includes(existing.replace(/\.ts$/, ''))) {
      unlinkSync(join(FIXTURES_DIR, existing));
      console.log(`- removed stale ${existing}`);
    }
  }

  writeFileSync(join(FIXTURES_DIR, 'index.ts'), renderIndex(ids), 'utf-8');
  console.log(`\nWrote ${ids.length} fixture(s) + index.ts to ${FIXTURES_DIR}`);
}

main();
