/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-004.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_004: AuthoredQuestionSet = {
  "questionSetId": "original-practice-004",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-28T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). G2 native-speaker review PENDING — do not seed or merge before it. Originality check against the Teacher's Notes text PENDING (the booklet was not available in the authoring session; run scripts/authoring/originalityCheck.ts before seeding). Role play: interview for a summer job at a campsite."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-004",
      "topicArea": "D",
      "title": "Un travail dans un camping",
      "setup": "Vous voulez travailler cet été dans un camping en France. Vous avez un entretien avec moi. Je dirige le camping.",
      "examinerRegister": "vous",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Bonjour. Quel âge avez-vous ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "Quelles langues parlez-vous ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Qu'avez-vous fait l'été dernier ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "C'était comment ?"
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Pourquoi voulez-vous travailler dans un camping ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Qu'aimeriez-vous faire ici ?"
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Quand pouvez-vous commencer ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Et combien de semaines pouvez-vous rester ?"
        }
      ]
    },
    "topic1": {
      "topicArea": "A",
      "subTopic": "Food and drink",
      "title": "Les repas",
      "furtherQuestions": [
        "Que manges-tu pendant les fêtes ?",
        "Comment peut-on manger plus sainement ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Que manges-tu le matin ?",
          "alternativeTexts": [],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Qui prépare le dîner chez toi ?",
          "alternativeTexts": [],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Parle-moi d'un bon repas que tu as mangé.",
          "secondPartText": "Où était-ce ?",
          "alternativeTexts": [
            "Qu'as-tu mangé hier soir ?",
            "Avec qui ?"
          ],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "core",
          "targetStructures": [
            "perfect",
            "imperfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "Que penses-tu des repas à la cantine ?",
          "alternativeTexts": [
            "Que manges-tu à midi ?"
          ],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Quel plat aimerais-tu faire goûter à un ami français ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Quel plat voudrais-tu apprendre à cuisiner ?",
            "Pourquoi ?"
          ],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "higher",
          "targetStructures": [
            "conditional",
            "justification"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 2
        }
      ]
    },
    "topic2": {
      "topicArea": "E",
      "subTopic": "Countries, nationalities and languages",
      "title": "Les langues et les pays",
      "furtherQuestions": [
        "Comment pratiques-tu le français en dehors de l'école ?",
        "Que sais-tu sur un pays francophone ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Quelles langues parle-t-on dans ton pays ?",
          "alternativeTexts": [],
          "topicArea": "E",
          "subTopic": "Countries, nationalities and languages",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Depuis combien de temps apprends-tu le français ?",
          "alternativeTexts": [],
          "topicArea": "E",
          "subTopic": "Countries, nationalities and languages",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Parle-moi d'un pays que tu as visité ou découvert à l'école.",
          "alternativeTexts": [
            "Qu'as-tu appris sur la France cette année ?"
          ],
          "topicArea": "E",
          "subTopic": "Countries, nationalities and languages",
          "difficulty": "core",
          "targetStructures": [
            "perfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 1
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "Pourquoi est-il utile d'apprendre une langue étrangère ?",
          "secondPartText": "Quelle autre langue voudrais-tu apprendre ?",
          "alternativeTexts": [
            "Aimes-tu apprendre le français ?",
            "Pourquoi ?"
          ],
          "topicArea": "E",
          "subTopic": "Countries, nationalities and languages",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "justification",
            "conditional"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Dans quel pays aimerais-tu habiter plus tard ?",
          "alternativeTexts": [
            "Quel pays voudrais-tu visiter ?"
          ],
          "topicArea": "E",
          "subTopic": "Countries, nationalities and languages",
          "difficulty": "higher",
          "targetStructures": [
            "conditional"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 1
        }
      ]
    }
  }
};
