/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-001.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_001: AuthoredQuestionSet = {
  "questionSetId": "original-practice-001",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-28T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). Originality check against the June 2026 Teacher's Notes text: clean (2026-09-28). G2 native-speaker review PENDING — do not seed or merge before it. Role play: a missed train at the station."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-001",
      "topicArea": "A",
      "title": "Un nouveau billet de train",
      "setup": "Vous êtes à la gare de Lyon, en France. Vous avez raté votre train pour Marseille et vous voulez un nouveau billet. Je travaille au guichet.",
      "examinerRegister": "vous",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Bonjour. Qu'est-ce que je peux faire pour vous ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "Vous voulez partir à quelle heure ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Pourquoi avez-vous raté votre train ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "À quelle heure êtes-vous arrivé(e) à la gare ?"
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Qu'allez-vous faire à Marseille ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Combien de temps allez-vous rester là-bas ?"
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Comment voulez-vous payer ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Et pour le retour, quel jour voulez-vous voyager ?"
        }
      ]
    },
    "topic1": {
      "topicArea": "A",
      "subTopic": "Travel and transport",
      "title": "Les transports",
      "furtherQuestions": [
        "Que penses-tu des bus et des trains dans ta région ?",
        "Comment les gens de ta famille se déplacent-ils ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Comment vas-tu à l'école le matin ?",
          "alternativeTexts": [],
          "topicArea": "A",
          "subTopic": "Travel and transport",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Combien de temps dure ton trajet pour aller à l'école ?",
          "alternativeTexts": [],
          "topicArea": "A",
          "subTopic": "Travel and transport",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Parle-moi d'un voyage que tu as fait.",
          "secondPartText": "Comment ça s'est passé ?",
          "alternativeTexts": [
            "Où es-tu allé(e) le week-end dernier ?",
            "Comment ça s'est passé ?"
          ],
          "topicArea": "A",
          "subTopic": "Travel and transport",
          "difficulty": "core",
          "targetStructures": [
            "perfect",
            "imperfect",
            "opinion"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "À ton avis, quel est le moyen de transport le plus pratique en ville ?",
          "alternativeTexts": [
            "Comment préfères-tu te déplacer en ville ?"
          ],
          "topicArea": "A",
          "subTopic": "Travel and transport",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "comparison"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Si tu pouvais faire un grand voyage, où irais-tu ?",
          "secondPartText": "Comment voyagerais-tu ?",
          "alternativeTexts": [
            "Quel pays voudrais-tu visiter un jour ?",
            "Pourquoi ?"
          ],
          "topicArea": "A",
          "subTopic": "Travel and transport",
          "difficulty": "higher",
          "targetStructures": [
            "conditional",
            "imperfect"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 2
        }
      ]
    },
    "topic2": {
      "topicArea": "C",
      "subTopic": "The natural world, the environment, the climate and the weather",
      "title": "L'environnement et la météo",
      "furtherQuestions": [
        "Quelle est la saison la plus agréable dans ta région ?",
        "Que penses-tu des voitures électriques ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Quel temps fait-il chez toi en été ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "The natural world, the environment, the climate and the weather",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Que fais-tu quand il fait beau ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "The natural world, the environment, the climate and the weather",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Raconte une journée où il a fait très mauvais temps.",
          "alternativeTexts": [
            "Qu'as-tu fait la dernière fois qu'il a plu ?"
          ],
          "topicArea": "C",
          "subTopic": "The natural world, the environment, the climate and the weather",
          "difficulty": "core",
          "targetStructures": [
            "perfect",
            "imperfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 1
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "Quel est le plus grand problème pour l'environnement aujourd'hui ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "La pollution est-elle un problème dans ta ville ?",
            "Pourquoi ?"
          ],
          "topicArea": "C",
          "subTopic": "The natural world, the environment, the climate and the weather",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Selon toi, comment sera le temps dans ta région dans cinquante ans ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Fera-t-il plus chaud ou plus froid plus tard chez toi ?",
            "Pourquoi ?"
          ],
          "topicArea": "C",
          "subTopic": "The natural world, the environment, the climate and the weather",
          "difficulty": "higher",
          "targetStructures": [
            "simple-future",
            "comparison",
            "justification"
          ],
          "expectedTimeFrame": "future",
          "partsExpected": 2
        }
      ]
    }
  }
};
