/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-008.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_008: AuthoredQuestionSet = {
  "questionSetId": "original-practice-008",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-28T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). Originality check against the June 2026 Teacher's Notes text: clean (2026-09-28). G2 native-speaker review PENDING — do not seed or merge before it. Role play: a friend organising a park clean-up."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-008",
      "topicArea": "C",
      "title": "Nettoyer le parc",
      "setup": "Vous êtes en France chez votre ami(e) Camille. Ce week-end, Camille organise le nettoyage du parc de son quartier. Je suis Camille.",
      "examinerRegister": "tu",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Salut ! Que fais-tu samedi matin ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "Que peux-tu apporter ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Comment va-t-on aller au parc ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Qu'as-tu déjà fait pour l'environnement ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Pourquoi c'est important pour toi ?"
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Samedi soir, que voudrais-tu faire pour fêter la fin du nettoyage ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Pourquoi ?"
        }
      ]
    },
    "topic1": {
      "topicArea": "A",
      "subTopic": "Food and drink",
      "title": "La cuisine et les courses",
      "furtherQuestions": [
        "Que sais-tu cuisiner ?",
        "Que penses-tu des repas rapides comme les hamburgers ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Où ta famille fait-elle les courses ?",
          "alternativeTexts": [],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Quel aliment ne manges-tu jamais ?",
          "alternativeTexts": [],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "foundation",
          "targetStructures": [
            "present",
            "negation"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Raconte comment tu as préparé un repas toi-même.",
          "secondPartText": "Qui t'a aidé(e) ?",
          "alternativeTexts": [
            "Qu'as-tu cuisiné récemment ?",
            "Qui t'a aidé(e) ?"
          ],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "core",
          "targetStructures": [
            "perfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "Vaut-il mieux faire les courses au marché ou au supermarché ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Aimes-tu aller au marché ?",
            "Pourquoi ?"
          ],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "comparison",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Quel plat prépareras-tu pour tes amis cet été ?",
          "alternativeTexts": [
            "Que vas-tu cuisiner ce week-end ?"
          ],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "higher",
          "targetStructures": [
            "simple-future"
          ],
          "expectedTimeFrame": "future",
          "partsExpected": 1
        }
      ]
    },
    "topic2": {
      "topicArea": "C",
      "subTopic": "People and places",
      "title": "Les gens de mon quartier",
      "furtherQuestions": [
        "Comment peut-on aider les personnes âgées de son quartier ?",
        "Quelle personne célèbre vient de ta région ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Qui sont tes voisins ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "People and places",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Comment sont les gens de ton quartier ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "People and places",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Décris un événement qui a eu lieu dans ton quartier.",
          "secondPartText": "Qui était là ?",
          "alternativeTexts": [
            "Quelle fête de quartier as-tu vue récemment ?",
            "Qui était là ?"
          ],
          "topicArea": "C",
          "subTopic": "People and places",
          "difficulty": "core",
          "targetStructures": [
            "perfect",
            "imperfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "Qu'est-ce qui rend un quartier agréable, à ton avis ?",
          "alternativeTexts": [
            "Que préfères-tu dans ton quartier ?"
          ],
          "topicArea": "C",
          "subTopic": "People and places",
          "difficulty": "core",
          "targetStructures": [
            "opinion"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Si un ami étranger venait chez toi, où l'emmènerais-tu ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Quel endroit de ta ville voudrais-tu montrer à un ami ?",
            "Pourquoi ?"
          ],
          "topicArea": "C",
          "subTopic": "People and places",
          "difficulty": "higher",
          "targetStructures": [
            "conditional",
            "imperfect",
            "justification"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 2
        }
      ]
    }
  }
};
