/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-003.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_003: AuthoredQuestionSet = {
  "questionSetId": "original-practice-003",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-29T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). Originality check against the June 2026 Teacher's Notes text: clean (2026-09-28). G2 waived by owner 2026-09-29; content is machine-authored and self-reviewed (G1). Role play: asking for information at a tourist office."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-003",
      "topicArea": "C",
      "title": "À l'office de tourisme",
      "setup": "Vous êtes en vacances dans une petite ville française. Vous allez à l'office de tourisme. Je travaille à l'office de tourisme.",
      "examinerRegister": "vous",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Bonjour. Quelles informations cherchez-vous ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "Vous restez combien de nuits ici ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Quelles activités aimez-vous faire en vacances ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Qu'avez-vous déjà visité dans la ville ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Qu'en avez-vous pensé ?"
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Que ferez-vous demain ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Pourquoi avez-vous choisi cette activité ?"
        }
      ]
    },
    "topic1": {
      "topicArea": "B",
      "subTopic": "Clothes and accessories",
      "title": "Les vêtements et la mode",
      "furtherQuestions": [
        "Que penses-tu de l'uniforme scolaire ?",
        "Quels accessoires aimes-tu porter ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Que portes-tu le week-end ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "Clothes and accessories",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Où achètes-tu tes vêtements ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "Clothes and accessories",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Quels vêtements as-tu achetés récemment ?",
          "alternativeTexts": [
            "Qu'as-tu porté hier ?"
          ],
          "topicArea": "B",
          "subTopic": "Clothes and accessories",
          "difficulty": "core",
          "targetStructures": [
            "perfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 1
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "La mode est-elle importante pour toi ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Aimes-tu acheter des vêtements ?",
            "Pourquoi ?"
          ],
          "topicArea": "B",
          "subTopic": "Clothes and accessories",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Que porteras-tu pour la prochaine fête de famille ?",
          "secondPartText": "Pourquoi ce choix ?",
          "alternativeTexts": [
            "Quels vêtements vas-tu mettre ce week-end ?",
            "Pourquoi ?"
          ],
          "topicArea": "B",
          "subTopic": "Clothes and accessories",
          "difficulty": "higher",
          "targetStructures": [
            "simple-future",
            "justification"
          ],
          "expectedTimeFrame": "future",
          "partsExpected": 2
        }
      ]
    },
    "topic2": {
      "topicArea": "D",
      "subTopic": "Education",
      "title": "L'école",
      "furtherQuestions": [
        "Que faudrait-il changer dans ton école ?",
        "Quelles activités y a-t-il après les cours dans ton école ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Combien de cours as-tu par jour ?",
          "alternativeTexts": [],
          "topicArea": "D",
          "subTopic": "Education",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Que fais-tu pendant la récréation ?",
          "alternativeTexts": [],
          "topicArea": "D",
          "subTopic": "Education",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Comment était ton école primaire ?",
          "secondPartText": "Qu'est-ce qui est différent maintenant ?",
          "alternativeTexts": [
            "Qui était ton professeur préféré à l'école primaire ?",
            "Pourquoi ?"
          ],
          "topicArea": "D",
          "subTopic": "Education",
          "difficulty": "core",
          "targetStructures": [
            "imperfect",
            "comparison"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "À ton avis, quels sont les avantages des devoirs ?",
          "secondPartText": "Et les inconvénients ?",
          "alternativeTexts": [
            "Aimes-tu faire tes devoirs ?",
            "Pourquoi ?"
          ],
          "topicArea": "D",
          "subTopic": "Education",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Que feras-tu après tes examens ?",
          "alternativeTexts": [
            "Quelles matières vas-tu étudier l'année prochaine ?"
          ],
          "topicArea": "D",
          "subTopic": "Education",
          "difficulty": "higher",
          "targetStructures": [
            "simple-future"
          ],
          "expectedTimeFrame": "future",
          "partsExpected": 1
        }
      ]
    }
  }
};
