/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-009.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_009: AuthoredQuestionSet = {
  "questionSetId": "original-practice-009",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-28T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). Originality check against the June 2026 Teacher's Notes text: clean (2026-09-28). G2 native-speaker review PENDING — do not seed or merge before it. Role play: first day at a French school, with a classmate."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-009",
      "topicArea": "D",
      "title": "Premier jour au collège",
      "setup": "Vous êtes dans un collège français pour une semaine d'échange. C'est votre premier jour. Je suis un(e) élève de votre classe.",
      "examinerRegister": "tu",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Salut ! Tu t'appelles comment ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "Tu es en France depuis quand ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Qu'as-tu pensé du cours de maths ce matin ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Pourquoi ?"
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Que vas-tu faire à midi ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Et après les cours, que voudrais-tu visiter ?"
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Comment est une journée typique dans ton école ?",
          "alternativeTexts": [],
          "partsExpected": 1
        }
      ]
    },
    "topic1": {
      "topicArea": "B",
      "subTopic": "Self, family and friends",
      "title": "Les amis",
      "furtherQuestions": [
        "Qui est la personne la plus importante dans ta vie ?",
        "Comment aides-tu tes amis quand ils ont un problème ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Comment es-tu de caractère ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "Self, family and friends",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Où vas-tu avec tes amis le week-end ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "Self, family and friends",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Comment as-tu rencontré ton meilleur ami ou ta meilleure amie ?",
          "alternativeTexts": [
            "Où as-tu rencontré tes amis ?"
          ],
          "topicArea": "B",
          "subTopic": "Self, family and friends",
          "difficulty": "core",
          "targetStructures": [
            "perfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 1
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "Est-il préférable d'avoir beaucoup d'amis ou quelques amis proches ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "As-tu beaucoup d'amis ?",
            "C'est important pour toi ?"
          ],
          "topicArea": "B",
          "subTopic": "Self, family and friends",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "comparison",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Comment vas-tu garder contact avec tes amis après le collège ?",
          "secondPartText": "Pourquoi est-ce important ?",
          "alternativeTexts": [
            "Que vas-tu faire avec tes amis cet été ?",
            "Pourquoi ?"
          ],
          "topicArea": "B",
          "subTopic": "Self, family and friends",
          "difficulty": "higher",
          "targetStructures": [
            "near-future",
            "justification"
          ],
          "expectedTimeFrame": "future",
          "partsExpected": 2
        }
      ]
    },
    "topic2": {
      "topicArea": "C",
      "subTopic": "The natural world, the environment, the climate and the weather",
      "title": "La nature et le climat",
      "furtherQuestions": [
        "Quel endroit naturel de ton pays est le plus beau ?",
        "Comment ta famille économise-t-elle l'eau ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Quels animaux vivent près de chez toi ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "The natural world, the environment, the climate and the weather",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Qu'aimes-tu faire dans la nature ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "The natural world, the environment, the climate and the weather",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Parle-moi d'une sortie dans la nature que tu as faite.",
          "secondPartText": "Avec qui étais-tu ?",
          "alternativeTexts": [
            "Quand es-tu allé(e) à la campagne ou à la plage ?",
            "Avec qui étais-tu ?"
          ],
          "topicArea": "C",
          "subTopic": "The natural world, the environment, the climate and the weather",
          "difficulty": "core",
          "targetStructures": [
            "perfect",
            "imperfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "Le climat de ton pays change-t-il ?",
          "secondPartText": "Comment le sais-tu ?",
          "alternativeTexts": [
            "Fait-il plus chaud qu'avant chez toi ?",
            "Pourquoi, à ton avis ?"
          ],
          "topicArea": "C",
          "subTopic": "The natural world, the environment, the climate and the weather",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "comparison",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Que ferais-tu pour protéger les animaux si tu avais le pouvoir ?",
          "alternativeTexts": [
            "Comment voudrais-tu aider les animaux ?"
          ],
          "topicArea": "C",
          "subTopic": "The natural world, the environment, the climate and the weather",
          "difficulty": "higher",
          "targetStructures": [
            "conditional",
            "imperfect"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 1
        }
      ]
    }
  }
};
