/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-010.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_010: AuthoredQuestionSet = {
  "questionSetId": "original-practice-010",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-28T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). G2 native-speaker review PENDING — do not seed or merge before it. Originality check against the Teacher's Notes text PENDING (the booklet was not available in the authoring session; run scripts/authoring/originalityCheck.ts before seeding). Role play: enrolling on a French course at a language school."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-010",
      "topicArea": "E",
      "title": "Un cours de français à Nice",
      "setup": "Vous voulez suivre un cours de français cet été dans une école de langues à Nice. Vous téléphonez à l'école. Je travaille à l'accueil de l'école.",
      "examinerRegister": "vous",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Bonjour. Quel est votre nom ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "De quelle nationalité êtes-vous ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Comment avez-vous appris le français jusqu'à maintenant ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Qu'est-ce qui a été difficile ?"
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Pourquoi voulez-vous suivre ce cours ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Et que voudriez-vous améliorer ?"
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Qu'allez-vous faire à Nice pendant votre temps libre ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Où allez-vous loger ?"
        }
      ]
    },
    "topic1": {
      "topicArea": "B",
      "subTopic": "Leisure time",
      "title": "La musique et le cinéma",
      "furtherQuestions": [
        "Quel instrument de musique aimerais-tu apprendre ?",
        "Comment découvres-tu de la nouvelle musique ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Quelle musique écoutes-tu ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "Leisure time",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Où regardes-tu des films ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "Leisure time",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Parle-moi d'un film que tu as vu récemment.",
          "secondPartText": "Qu'en as-tu pensé ?",
          "alternativeTexts": [
            "Quel film as-tu regardé le week-end dernier ?",
            "Il était comment ?"
          ],
          "topicArea": "B",
          "subTopic": "Leisure time",
          "difficulty": "core",
          "targetStructures": [
            "perfect",
            "imperfect",
            "opinion"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "Quels sont les avantages du cinéma par rapport à la télévision ?",
          "alternativeTexts": [
            "Où préfères-tu regarder des films ?"
          ],
          "topicArea": "B",
          "subTopic": "Leisure time",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "comparison"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Si tu pouvais rencontrer un chanteur ou un acteur, qui choisirais-tu ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Quel concert aimerais-tu voir ?",
            "Pourquoi ?"
          ],
          "topicArea": "B",
          "subTopic": "Leisure time",
          "difficulty": "higher",
          "targetStructures": [
            "conditional",
            "imperfect",
            "justification"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 2
        }
      ]
    },
    "topic2": {
      "topicArea": "D",
      "subTopic": "Work",
      "title": "Le travail et l'avenir",
      "furtherQuestions": [
        "Que penses-tu du travail le week-end pour les étudiants ?",
        "Quelles qualités faut-il pour trouver un bon travail ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Quel métier trouves-tu intéressant ?",
          "alternativeTexts": [],
          "topicArea": "D",
          "subTopic": "Work",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Qui t'aide à choisir ton futur métier ?",
          "alternativeTexts": [],
          "topicArea": "D",
          "subTopic": "Work",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Quel métier voulais-tu faire quand tu étais petit(e) ?",
          "alternativeTexts": [
            "Tu voulais faire quel travail à six ans ?"
          ],
          "topicArea": "D",
          "subTopic": "Work",
          "difficulty": "core",
          "targetStructures": [
            "imperfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 1
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "Quels sont les avantages de travailler dans un autre pays ?",
          "secondPartText": "Et les inconvénients ?",
          "alternativeTexts": [
            "Qu'est-ce qui est bien quand on travaille à l'étranger ?",
            "Et qu'est-ce qui est difficile ?"
          ],
          "topicArea": "D",
          "subTopic": "Work",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "comparison"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Où travailleras-tu dans dix ans ?",
          "secondPartText": "Que feras-tu exactement ?",
          "alternativeTexts": [
            "Quel travail vas-tu chercher plus tard ?",
            "Pourquoi ?"
          ],
          "topicArea": "D",
          "subTopic": "Work",
          "difficulty": "higher",
          "targetStructures": [
            "simple-future"
          ],
          "expectedTimeFrame": "future",
          "partsExpected": 2
        }
      ]
    }
  }
};
