/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-007.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_007: AuthoredQuestionSet = {
  "questionSetId": "original-practice-007",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-28T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). Originality check against the June 2026 Teacher's Notes text: clean (2026-09-28). G2 native-speaker review PENDING — do not seed or merge before it. Role play: shopping for clothes with a French friend."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-007",
      "topicArea": "B",
      "title": "Des vêtements pour une fête",
      "setup": "Vous êtes en France. Vous faites les magasins avec votre ami(e) Camille parce que vous allez à une fête samedi. Je suis Camille.",
      "examinerRegister": "tu",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Alors, que cherches-tu ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "Quelle est ta taille ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Qu'as-tu porté pour ta dernière fête ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Comment s'est passée cette fête ?"
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Tu préfères ce pull bleu ou ce t-shirt noir ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Pourquoi ?"
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Samedi, comment vas-tu aller à la fête ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "À quelle heure veux-tu rentrer ?"
        }
      ]
    },
    "topic1": {
      "topicArea": "B",
      "subTopic": "Leisure time",
      "title": "Les loisirs",
      "furtherQuestions": [
        "Combien de temps libre as-tu pendant la semaine ?",
        "Quel loisir coûte trop cher, à ton avis ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Que fais-tu après l'école ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "Leisure time",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Avec qui passes-tu ton temps libre ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "Leisure time",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Que faisais-tu le week-end quand tu avais dix ans ?",
          "secondPartText": "Et maintenant ?",
          "alternativeTexts": [
            "À quoi jouais-tu à l'école primaire ?",
            "Et maintenant ?"
          ],
          "topicArea": "B",
          "subTopic": "Leisure time",
          "difficulty": "core",
          "targetStructures": [
            "imperfect",
            "present",
            "comparison"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "Quels sont les avantages des activités en plein air ?",
          "alternativeTexts": [
            "Quelle activité en plein air aimes-tu ?"
          ],
          "topicArea": "B",
          "subTopic": "Leisure time",
          "difficulty": "core",
          "targetStructures": [
            "opinion"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Que feras-tu pendant les prochaines vacances ?",
          "secondPartText": "Avec qui ?",
          "alternativeTexts": [
            "Que vas-tu faire ce week-end ?",
            "Avec qui ?"
          ],
          "topicArea": "B",
          "subTopic": "Leisure time",
          "difficulty": "higher",
          "targetStructures": [
            "simple-future"
          ],
          "expectedTimeFrame": "future",
          "partsExpected": 2
        }
      ]
    },
    "topic2": {
      "topicArea": "E",
      "subTopic": "Culture, customs, faiths and celebrations",
      "title": "Les fêtes et les traditions",
      "furtherQuestions": [
        "Quelle tradition de ta famille aimerais-tu garder plus tard ?",
        "Comment décore-t-on les maisons pour les fêtes chez toi ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Quelle est ta fête préférée ?",
          "alternativeTexts": [],
          "topicArea": "E",
          "subTopic": "Culture, customs, faiths and celebrations",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Comment fête-t-on les anniversaires dans ta famille ?",
          "alternativeTexts": [],
          "topicArea": "E",
          "subTopic": "Culture, customs, faiths and celebrations",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Comment as-tu fêté ton dernier anniversaire ?",
          "alternativeTexts": [
            "Qui était à ton dernier anniversaire ?"
          ],
          "topicArea": "E",
          "subTopic": "Culture, customs, faiths and celebrations",
          "difficulty": "core",
          "targetStructures": [
            "perfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 1
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "Quelle tradition de ton pays trouves-tu la plus belle ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Quelle fête de ton pays aimes-tu ?",
            "Pourquoi ?"
          ],
          "topicArea": "E",
          "subTopic": "Culture, customs, faiths and celebrations",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Quelle fête d'un autre pays aimerais-tu vivre un jour ?",
          "secondPartText": "Avec qui voudrais-tu y aller ?",
          "alternativeTexts": [
            "Quelle fête étrangère voudrais-tu découvrir ?",
            "Avec qui ?"
          ],
          "topicArea": "E",
          "subTopic": "Culture, customs, faiths and celebrations",
          "difficulty": "higher",
          "targetStructures": [
            "conditional"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 2
        }
      ]
    }
  }
};
