/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-002.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_002: AuthoredQuestionSet = {
  "questionSetId": "original-practice-002",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-28T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). G2 native-speaker review PENDING — do not seed or merge before it. Originality check against the Teacher's Notes text PENDING (the booklet was not available in the authoring session; run scripts/authoring/originalityCheck.ts before seeding). Role play: planning an outing with a French friend."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-002",
      "topicArea": "B",
      "title": "Une sortie avec Camille",
      "setup": "Tu es en France chez ton ami(e) Camille. Tu organises une sortie avec Camille pour samedi. Je suis Camille.",
      "examinerRegister": "tu",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Salut ! Qu'est-ce que tu veux faire samedi ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "On se retrouve à quelle heure ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Qu'as-tu fait le week-end dernier ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Avec qui ?"
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Comment est-ce qu'on va aller en ville ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Après la sortie, qu'aimerais-tu manger ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Pourquoi ?"
        }
      ]
    },
    "topic1": {
      "topicArea": "B",
      "subTopic": "In the home",
      "title": "La maison",
      "furtherQuestions": [
        "Dans quelle pièce passes-tu le plus de temps ?",
        "Que fais-tu le soir à la maison ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Qu'y a-t-il dans ta chambre ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "In the home",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Qui fait le ménage chez toi ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "In the home",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Comment as-tu aidé à la maison le week-end dernier ?",
          "secondPartText": "C'était comment ?",
          "alternativeTexts": [
            "Quelle tâche ménagère as-tu faite hier ?",
            "C'était comment ?"
          ],
          "topicArea": "B",
          "subTopic": "In the home",
          "difficulty": "core",
          "targetStructures": [
            "perfect",
            "imperfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "Qu'est-ce que tu aimes dans ta maison ?",
          "secondPartText": "Et qu'est-ce que tu n'aimes pas ?",
          "alternativeTexts": [
            "Quelle pièce de ta maison préfères-tu ?",
            "Et quelle pièce n'aimes-tu pas ?"
          ],
          "topicArea": "B",
          "subTopic": "In the home",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "negation"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Comment serait ta maison idéale ?",
          "alternativeTexts": [
            "Quelle maison voudrais-tu avoir plus tard ?"
          ],
          "topicArea": "B",
          "subTopic": "In the home",
          "difficulty": "higher",
          "targetStructures": [
            "conditional"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 1
        }
      ]
    },
    "topic2": {
      "topicArea": "C",
      "subTopic": "Communications and technology",
      "title": "La technologie",
      "furtherQuestions": [
        "Que fais-tu pour te protéger en ligne ?",
        "Comment contactes-tu ta famille pendant la journée ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Qu'est-ce que tu fais sur Internet ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "Communications and technology",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Quelle application utilises-tu le plus souvent ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "Communications and technology",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Comment communiquais-tu avec tes amis quand tu étais petit(e) ?",
          "secondPartText": "Et maintenant ?",
          "alternativeTexts": [
            "Avais-tu un téléphone quand tu avais dix ans ?",
            "Et maintenant ?"
          ],
          "topicArea": "C",
          "subTopic": "Communications and technology",
          "difficulty": "core",
          "targetStructures": [
            "imperfect",
            "present",
            "comparison"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "Quels sont les dangers des réseaux sociaux pour les jeunes ?",
          "alternativeTexts": [
            "Que penses-tu des réseaux sociaux ?"
          ],
          "topicArea": "C",
          "subTopic": "Communications and technology",
          "difficulty": "core",
          "targetStructures": [
            "opinion"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Quelle nouvelle technologie aimerais-tu avoir dans le futur ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Quel téléphone voudrais-tu avoir ?",
            "Pourquoi ?"
          ],
          "topicArea": "C",
          "subTopic": "Communications and technology",
          "difficulty": "higher",
          "targetStructures": [
            "conditional",
            "justification"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 2
        }
      ]
    }
  }
};
