/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-005.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_005: AuthoredQuestionSet = {
  "questionSetId": "original-practice-005",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-28T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). Originality check against the June 2026 Teacher's Notes text: clean (2026-09-28). G2 native-speaker review PENDING — do not seed or merge before it. Role play: a French friend's family celebration."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-005",
      "topicArea": "E",
      "title": "Une fête de famille en France",
      "setup": "Vous passez une semaine chez votre ami(e) Camille, en France. Ce soir, sa famille fait une grande fête. Je suis Camille.",
      "examinerRegister": "tu",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Salut ! Tu vas porter quoi ce soir ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "Comment peux-tu m'aider à préparer la fête ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Quelle fête as-tu célébrée récemment chez toi ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Qu'as-tu mangé ce jour-là ?"
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Quelle fête française aimerais-tu découvrir ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Pourquoi ?"
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Demain, on va au marché. Que voudrais-tu acheter ?",
          "alternativeTexts": [],
          "partsExpected": 1
        }
      ]
    },
    "topic1": {
      "topicArea": "B",
      "subTopic": "Self, family and friends",
      "title": "La famille et les amis",
      "furtherQuestions": [
        "Comment t'entends-tu avec tes parents ?",
        "Que fais-tu quand tu te disputes avec un ami ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Avec qui habites-tu ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "Self, family and friends",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Qui est ton meilleur ami ou ta meilleure amie ?",
          "alternativeTexts": [],
          "topicArea": "B",
          "subTopic": "Self, family and friends",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Qu'as-tu fait avec ta famille le week-end dernier ?",
          "secondPartText": "Comment ça s'est passé ?",
          "alternativeTexts": [
            "Où es-tu allé(e) avec ta famille récemment ?",
            "Comment ça s'est passé ?"
          ],
          "topicArea": "B",
          "subTopic": "Self, family and friends",
          "difficulty": "core",
          "targetStructures": [
            "perfect",
            "imperfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "Qu'est-ce qui est important dans une amitié ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Qu'aimes-tu faire avec tes amis ?",
            "Pourquoi ?"
          ],
          "topicArea": "B",
          "subTopic": "Self, family and friends",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Comment imagines-tu ta vie de famille dans quinze ans ?",
          "alternativeTexts": [
            "Où vas-tu habiter plus tard ?"
          ],
          "topicArea": "B",
          "subTopic": "Self, family and friends",
          "difficulty": "higher",
          "targetStructures": [
            "simple-future",
            "near-future"
          ],
          "expectedTimeFrame": "future",
          "partsExpected": 1
        }
      ]
    },
    "topic2": {
      "topicArea": "C",
      "subTopic": "The built environment",
      "title": "La ville",
      "furtherQuestions": [
        "Comment peut-on rendre une ville plus agréable ?",
        "Quel monument célèbre aimerais-tu visiter ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Quels bâtiments y a-t-il près de chez toi ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "The built environment",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Quel est ton endroit préféré en ville ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "The built environment",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Comment était ta ville il y a dix ans ?",
          "secondPartText": "Qu'est-ce qui a changé ?",
          "alternativeTexts": [
            "Quel magasin aimais-tu à l'âge de sept ans ?",
            "Pourquoi ?"
          ],
          "topicArea": "C",
          "subTopic": "The built environment",
          "difficulty": "core",
          "targetStructures": [
            "imperfect",
            "perfect",
            "comparison"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "Qu'est-ce qui manque dans ta ville pour les jeunes ?",
          "alternativeTexts": [
            "Quel endroit n'existe pas dans ta ville ?"
          ],
          "topicArea": "C",
          "subTopic": "The built environment",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "negation"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Si tu étais maire, quel bâtiment construirais-tu ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Que voudrais-tu avoir de nouveau dans ta ville ?",
            "Pourquoi ?"
          ],
          "topicArea": "C",
          "subTopic": "The built environment",
          "difficulty": "higher",
          "targetStructures": [
            "conditional",
            "imperfect",
            "justification"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 2
        }
      ]
    }
  }
};
