/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-006.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_006: AuthoredQuestionSet = {
  "questionSetId": "original-practice-006",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-28T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). Originality check against the June 2026 Teacher's Notes text: clean (2026-09-28). G2 native-speaker review PENDING — do not seed or merge before it. Role play: ordering a meal in a restaurant."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-006",
      "topicArea": "A",
      "title": "Au restaurant",
      "setup": "Vous êtes dans un restaurant en France avec votre famille. Je travaille dans ce restaurant.",
      "examinerRegister": "vous",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Bonsoir. Vous êtes combien ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "Que voulez-vous boire ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Qu'allez-vous prendre comme plat principal ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Quels aliments ne mangez-vous pas ?"
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Comment avez-vous connu notre restaurant ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Qu'avez-vous préféré dans le repas ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Pourquoi ?"
        }
      ]
    },
    "topic1": {
      "topicArea": "A",
      "subTopic": "The human body and health",
      "title": "La santé",
      "furtherQuestions": [
        "Qu'est-ce qui est mauvais pour la santé, à ton avis ?",
        "Combien d'eau bois-tu par jour ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Combien d'heures dors-tu la nuit ?",
          "alternativeTexts": [],
          "topicArea": "A",
          "subTopic": "The human body and health",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Que manges-tu pour être en bonne santé ?",
          "alternativeTexts": [],
          "topicArea": "A",
          "subTopic": "The human body and health",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Raconte une fois où tu as été malade.",
          "alternativeTexts": [
            "Quand es-tu allé(e) chez le médecin ?"
          ],
          "topicArea": "A",
          "subTopic": "The human body and health",
          "difficulty": "core",
          "targetStructures": [
            "perfect",
            "imperfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 1
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "Quelles sont les causes du stress chez les jeunes ?",
          "secondPartText": "Comment peut-on l'éviter ?",
          "alternativeTexts": [
            "Qu'est-ce qui te stresse ?",
            "Que fais-tu contre le stress ?"
          ],
          "topicArea": "A",
          "subTopic": "The human body and health",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Quelle habitude vas-tu prendre pour mieux dormir ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "À quelle heure vas-tu te coucher ce soir ?",
            "Pourquoi ?"
          ],
          "topicArea": "A",
          "subTopic": "The human body and health",
          "difficulty": "higher",
          "targetStructures": [
            "near-future",
            "comparison",
            "justification"
          ],
          "expectedTimeFrame": "future",
          "partsExpected": 2
        }
      ]
    },
    "topic2": {
      "topicArea": "D",
      "subTopic": "Work",
      "title": "Le monde du travail",
      "furtherQuestions": [
        "Que penses-tu du travail à la maison ?",
        "Quel métier ne voudrais-tu jamais faire ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Quel travail fait un adulte que tu connais ?",
          "alternativeTexts": [],
          "topicArea": "D",
          "subTopic": "Work",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Quels petits boulots peuvent faire les jeunes de ton âge ?",
          "alternativeTexts": [],
          "topicArea": "D",
          "subTopic": "Work",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Quel métier as-tu découvert récemment ?",
          "secondPartText": "Comment l'as-tu découvert ?",
          "alternativeTexts": [
            "Quel métier as-tu vu dans un film ou à la télé ?",
            "Qu'en as-tu pensé ?"
          ],
          "topicArea": "D",
          "subTopic": "Work",
          "difficulty": "core",
          "targetStructures": [
            "perfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "À ton avis, pourquoi le travail en équipe est-il utile ?",
          "secondPartText": "Et quand est-il difficile ?",
          "alternativeTexts": [
            "Aimes-tu travailler en groupe à l'école ?",
            "Pourquoi ?"
          ],
          "topicArea": "D",
          "subTopic": "Work",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Quel métier choisirais-tu si tu pouvais faire n'importe lequel ?",
          "alternativeTexts": [
            "Dans quel métier aimerais-tu travailler ?"
          ],
          "topicArea": "D",
          "subTopic": "Work",
          "difficulty": "higher",
          "targetStructures": [
            "conditional",
            "imperfect"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 1
        }
      ]
    }
  }
};
