/**
 * GENERATED by scripts/authoring/generateFixtures.ts from french-coach-backend's
 * data/igcse/original-practice-008.json (the canonical authored source). Do not edit by hand:
 * edit the JSON, run `npm run authoring:generate`, then `npm run authoring:parity`.
 */

import type { AuthoredQuestionSet } from '../types';

export const ORIGINAL_PRACTICE_008: AuthoredQuestionSet = {
  "questionSetId": "original-practice-008",
  "schemaVersion": "question-bank-v1",
  "provenance": "original-practice",
  "review": {
    "status": "approved",
    "reviewedBy": "internal:claude",
    "reviewedAt": "2026-09-28T00:00:00.000Z",
    "notes": "Rewritten in the 0520 conduct plan, Batch 5: structure modeled on the 0520/03 Teacher/Examiner Notes (June 2026) per ADR 0008, wording original. G1 self-review done (internal:claude). G2 native-speaker review PENDING — do not seed or merge before it. Originality check against the Teacher's Notes text PENDING (the booklet was not available in the authoring session; run scripts/authoring/originalityCheck.ts before seeding). Role play: a friend organising a park clean-up."
  },
  "content": {
    "rolePlay": {
      "scenarioId": "rp-original-practice-008",
      "topicArea": "C",
      "title": "Nettoyer le parc",
      "setup": "Tu es en France chez ton ami(e) Camille. Ce week-end, Camille organise le nettoyage du parc de son quartier. Je suis Camille.",
      "examinerRegister": "tu",
      "tasks": [
        {
          "questionId": "rp1",
          "part": "rolePlay",
          "mainText": "Salut ! Que fais-tu samedi matin ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp2",
          "part": "rolePlay",
          "mainText": "Qu'est-ce que tu peux apporter ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp3",
          "part": "rolePlay",
          "mainText": "Comment est-ce qu'on va aller au parc ?",
          "alternativeTexts": [],
          "partsExpected": 1
        },
        {
          "questionId": "rp4",
          "part": "rolePlay",
          "mainText": "Qu'as-tu déjà fait pour l'environnement ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Pourquoi c'est important pour toi ?"
        },
        {
          "questionId": "rp5",
          "part": "rolePlay",
          "mainText": "Qu'est-ce qu'on pourrait faire après le nettoyage ?",
          "alternativeTexts": [],
          "partsExpected": 2,
          "secondPartText": "Et pour manger, que proposes-tu ?"
        }
      ]
    },
    "topic1": {
      "topicArea": "A",
      "subTopic": "Food and drink",
      "title": "La cuisine et les courses",
      "furtherQuestions": [
        "Que sais-tu cuisiner ?",
        "Que penses-tu de la nourriture végétarienne ?"
      ],
      "questions": [
        {
          "questionId": "t1q1",
          "part": "topic1",
          "mainText": "Où ta famille fait-elle les courses ?",
          "alternativeTexts": [],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q2",
          "part": "topic1",
          "mainText": "Qu'est-ce que tu ne manges jamais ?",
          "alternativeTexts": [],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "foundation",
          "targetStructures": [
            "present",
            "negation"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t1q3",
          "part": "topic1",
          "mainText": "Raconte la dernière fois que tu as préparé un repas.",
          "secondPartText": "Qui t'a aidé(e) ?",
          "alternativeTexts": [
            "Qu'as-tu cuisiné récemment ?",
            "Qui t'a aidé(e) ?"
          ],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "core",
          "targetStructures": [
            "perfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t1q4",
          "part": "topic1",
          "mainText": "Vaut-il mieux faire les courses au marché ou au supermarché ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Aimes-tu aller au marché ?",
            "Pourquoi ?"
          ],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "core",
          "targetStructures": [
            "opinion",
            "comparison",
            "justification"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 2
        },
        {
          "questionId": "t1q5",
          "part": "topic1",
          "mainText": "Que mangeras-tu pour ton prochain anniversaire ?",
          "alternativeTexts": [
            "Que vas-tu manger ce soir ?"
          ],
          "topicArea": "A",
          "subTopic": "Food and drink",
          "difficulty": "higher",
          "targetStructures": [
            "simple-future"
          ],
          "expectedTimeFrame": "future",
          "partsExpected": 1
        }
      ]
    },
    "topic2": {
      "topicArea": "C",
      "subTopic": "People and places",
      "title": "Ma région",
      "furtherQuestions": [
        "Quels sont les avantages de vivre à la campagne ?",
        "Quelle personne célèbre vient de ta région ?"
      ],
      "questions": [
        {
          "questionId": "t2q1",
          "part": "topic2",
          "mainText": "Dans quelle région habites-tu ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "People and places",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q2",
          "part": "topic2",
          "mainText": "Comment sont les gens de ton quartier ?",
          "alternativeTexts": [],
          "topicArea": "C",
          "subTopic": "People and places",
          "difficulty": "foundation",
          "targetStructures": [
            "present"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q3",
          "part": "topic2",
          "mainText": "Quel endroit de ta région as-tu visité récemment ?",
          "secondPartText": "Qu'as-tu fait là-bas ?",
          "alternativeTexts": [
            "Quel parc ou quel musée près de chez toi as-tu visité ?",
            "Qu'as-tu fait ?"
          ],
          "topicArea": "C",
          "subTopic": "People and places",
          "difficulty": "core",
          "targetStructures": [
            "perfect"
          ],
          "expectedTimeFrame": "past",
          "partsExpected": 2
        },
        {
          "questionId": "t2q4",
          "part": "topic2",
          "mainText": "Qu'est-ce qu'il faut voir dans ta région, à ton avis ?",
          "alternativeTexts": [
            "Quel est le plus bel endroit de ta région ?"
          ],
          "topicArea": "C",
          "subTopic": "People and places",
          "difficulty": "core",
          "targetStructures": [
            "opinion"
          ],
          "expectedTimeFrame": "present",
          "partsExpected": 1
        },
        {
          "questionId": "t2q5",
          "part": "topic2",
          "mainText": "Si un ami étranger venait chez toi, où l'emmènerais-tu ?",
          "secondPartText": "Pourquoi ?",
          "alternativeTexts": [
            "Quel endroit de ta ville voudrais-tu montrer à un ami ?",
            "Pourquoi ?"
          ],
          "topicArea": "C",
          "subTopic": "People and places",
          "difficulty": "higher",
          "targetStructures": [
            "conditional",
            "imperfect",
            "justification"
          ],
          "expectedTimeFrame": "conditional",
          "partsExpected": 2
        }
      ]
    }
  }
};
